from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
CPPPATH += [cwd + "/src"]
CPPPATH += [cwd + "/inc"]
src     = Glob('src/*.c')

libs = DefineGroup('libs', src, depend = [''], CPPPATH = CPPPATH)

Return('libs')
