from building import *
import os
from rtconfig import SDK_ROOT

cwd     = GetCurrentDir()
CPPPATH = [
    cwd,
    os.path.join(SDK_ROOT, 'common'),
]

src     = Glob('*.c')

group = DefineGroup('Bootloader', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
